version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
handlers:
  logfile:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./logs.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8
  console:
    class: logging.StreamHandler
    level: WARN
    formatter: simple
    stream: ext://sys.stdout
loggers:
  { { cookiecutter.project_dir } }:
    level: INFO
    handlers: [logfile, console]
    propagate: yes
